/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario_emanuel;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author crema
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar1
     */
    public Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        lemail = new javax.swing.JLabel();
        lpass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fnombre = new javax.swing.JTextField();
        femail = new javax.swing.JTextField();
        fpass = new javax.swing.JPasswordField();
        fconfirm = new javax.swing.JPasswordField();
        btnacept = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Agregar nuevo Usuario");

        lname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lname.setText("Nombre");

        lemail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lemail.setText("email");

        lpass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lpass.setText("Contraseña");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Confirmar");

        btnacept.setText("Aceptar");
        btnacept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptActionPerformed(evt);
            }
        });

        btncancel.setText("Cancelar");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lname)
                    .addComponent(lemail)
                    .addComponent(lpass)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fconfirm)
                    .addComponent(fpass)
                    .addComponent(femail)
                    .addComponent(fnombre))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnacept)
                        .addGap(61, 61, 61)
                        .addComponent(btncancel)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(title)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname)
                    .addComponent(fnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lemail)
                    .addComponent(femail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpass)
                    .addComponent(fpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnacept)
                    .addComponent(btncancel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertarUsuario(String nombre, String email, String password) {
    Connection conexion = null;
    PreparedStatement stmt = null;
    
    try {
        // 1. Obtener una conexión a la base de datos
        conexion = DriverManager.getConnection("jdbc:mysql://localhost/Usuarios", "root", "");
        
        // 2. Preparar la consulta SQL
        String sql = "INSERT INTO users (nombre, email, contraseña) VALUES (?, ?, ?)";
        stmt = conexion.prepareStatement(sql);
        stmt.setString(1, nombre);
        stmt.setString(2, email);
        stmt.setString(3, password);
        
        // 3. Ejecutar la consulta SQL
        stmt.executeUpdate();
        
        // 4. Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "El usuario se ha registrado exitosamente.");
        
    } catch (SQLException ex) {
        // Mostrar mensaje de error si ocurre una excepción SQL
        JOptionPane.showMessageDialog(this, "Error al registrar el usuario:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
    } finally {
        // 5. Cerrar la conexión y el statement
        if (stmt != null) {
            try {
                stmt.close();
            } catch (SQLException ex) {
                // Ignorar excepción al cerrar el statement
            }
        }
        
        if (conexion != null) {
            try {
                conexion.close();
            } catch (SQLException ex) {
                // Ignorar excepción al cerrar la conexión
            }
        }
    }
}
    
    
    
    private void btnaceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptActionPerformed
        
        String nombre = fnombre.getText();
        String email = femail.getText();
        String pass = fpass.getText();
        String confirm = String.valueOf(fconfirm.getPassword());

        if (nombre.equals("") || email.equals("") || pass.equals("") || confirm.equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        } else if (!pass.equals(confirm)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        } else {
            // Validación de formato de correo electrónico
            if (!email.matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")) {
                JOptionPane.showMessageDialog(null, "El formato del correo electrónico no es válido");
                return;
            }

            // Validación de mayúscula en la inicial de cada palabra
            String[] palabras = nombre.split(" ");
            for (String palabra : palabras) {
                if (!Character.isUpperCase(palabra.charAt(0))) {
                    JOptionPane.showMessageDialog(null, "El nombre debe empezar con mayúscula en la inicial de cada palabra");
                    return;
                }
            }

            // Llamada al método para insertar el usuario en la base de datos
            insertarUsuario(nombre, email, pass);
        }
    }//GEN-LAST:event_btnaceptActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, 
            "¿Está seguro de que desea cerrar la ventana?", "Confirmar cierre", 
            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmed == JOptionPane.YES_OPTION) {
            // Si el usuario ha confirmado, cierra la ventana
            this.dispose();
            // Mostrar la ventana anterior (VentanaPrincipal)
            Listado listado = new Listado();
            listado.setVisible(true);
        } else {
        // Si el usuario ha cancelado, no hace nada y deja la ventana abierta
        // (para cancelar el cierre de la ventana, se puede utilizar: evt.getWindow().setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE))
        }
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacept;
    private javax.swing.JButton btncancel;
    private javax.swing.JPasswordField fconfirm;
    private javax.swing.JTextField femail;
    private javax.swing.JTextField fnombre;
    private javax.swing.JPasswordField fpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lpass;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
